---
- name: Execute apt update and upgrade
  tags: ["all"]
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - git
    state: latest
  retries: 5
  delay: 2

- name: Import Docker repository GPG key
  tags: ["all"]
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Add Docker repository to Apt sources
  tags: ["all"]
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    create: yes

- name: Ensure Docker related packages are installed
  tags: ["all"]
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
